FROM python:3.10-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir -e .

COPY inventory_api/ /app/inventory_api/
COPY shared/ /app/shared/

COPY alembic.ini /app/alembic.ini
COPY migrations/ /app/migrations/
COPY tests/ /app/tests/

ENV PYTHONPATH=/app


CMD ["python", "-m", "inventory_api.app"]